language: rust
rust: 1.31.0
sudo: true
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo

if: 'branch = master OR type != push OR fork = true OR tag =~ ^v'

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - os: windows

script:
- cargo test -- --nocapture

before_cache:
- rm -rf $HOME/.cargo/registry
