platform:
  - x64
environment:
  RUST_INSTALL_DIR: C:\Rust
  matrix:
    - RUST_INSTALL_TRIPLE: i686-pc-windows-msvc
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"
      RUST_VERSION: 1.46.0
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
      RUST_VERSION: 1.46.0

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/${env:RUST_INSTALL_TRIPLE}/rustup-init.exe"
  - cmd: rustup-init.exe -yv --default-toolchain %RUST_VERSION% --default-host %RUST_INSTALL_TRIPLE%
  - cmd: CALL "%VCVARS%"
  - cmd: SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc --version
  - cargo --version

build: false
test_script:
  - cmd: SET RUST_BACKTRACE=full
  - cargo test
  - cmd: SET "RUSTDOCFLAGS=--cfg disable_faketime"
  - cmd: SET "RUSTFLAGS=--cfg disable_faketime"
  - cargo test
